[colors]
background = "#101010"
foreground = "#9A8F8A"

cursor_fg = "#101010"
cursor_bg = "#D27E99"
cursor_border = "#D27E99"

selection_bg = "#232325"

ansi = [
	"#0A0A0A",
	"#945B5B",
	"#737c73",
	"#B7927B",
	"#627691",
	"#be8c8c",
	"#8EA4A2",
	"#90847f",
]

brights = [
	"#272830",
	"#9c6363",
	"#8f9d85",
	"#b99b88",
	"#6e7f96",
	"#baa0a7",
	"#98a9a7",
	"#9A8F8A",
]
