[colors]
foreground = "#C5C9C5"
background = "#181616"

cursor_bg = "#b6927b"
cursor_border = "#b6927b"
selection_bg = "#282727"

ansi = [
	"#1D1C19",
	"#c4746e",
	"#8a9a7b",
	"#b6927b",
	"#627691",
	"#A292A3",
	"#8ba4b0",
	"#9e9b93",
]

brights = [
	"#272830",
	'#E46876',
	'#87A987',
	'#b6927b',
	'#8ba4b0',
	'#938AA9',
	'#7AA89F',
	'#a3a8a3',
]
